# -*- coding: utf-8 -*-
"""Tugas PAA II Tasya Mulfiana_F55121019.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RNc5TgYUIqirv-9hdl8mkkFXD41qYxhh

VERSI CEPAT
"""

import time

def bubble_sort(arr):
    n = len(arr)
    swapped = True
    while swapped:
        swapped = False
        for i in range(1, n):
            if arr[i-1] > arr[i]:
                arr[i-1], arr[i] = arr[i], arr[i-1]
                swapped = True
        n -= 1

# Fungsi untuk mengukur waktu eksekusi
def measure_time(arr):
    start_time = time.time()
    bubble_sort(arr)
    end_time = time.time()
    execution_time = end_time - start_time
    return execution_time

# Contoh penggunaan
array = [64, 34, 25, 12, 22, 11, 90]
print("Array sebelum diurutkan:", array)
time_taken = measure_time(array)
print("Array setelah diurutkan:", array)
print("Waktu eksekusi: %.6f detik" % time_taken)

"""VERSI LAMBAT"""

import time

def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]

# Fungsi untuk mengukur waktu eksekusi
def measure_time(arr):
    start_time = time.time()
    bubble_sort(arr)
    end_time = time.time()
    execution_time = end_time - start_time
    return execution_time

# Contoh penggunaan
array = [64, 34, 25, 12, 22, 11, 90]
print("Array sebelum diurutkan:", array)
time_taken = measure_time(array)
print("Array setelah diurutkan:", array)
print("Waktu eksekusi: %.6f detik" % time_taken)